<div class="wrap">
    <h1><?php echo esc_html__('2FA Verification', 'ebakim-wp'); ?></h1>

    <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
        <input type="hidden" name="action" value="custom_2fa_verification">

        <p><?php echo esc_html__('Please enter the 2FA code generated by your authenticator app.', 'ebakim-wp'); ?></p>

        <label for="2fa_code"><?php echo esc_html__('Enter 2FA Code', 'ebakim-wp'); ?></label>
        <input type="text" name="2fa_code" id="2fa_code" required>

        <p><em><?php echo esc_html__('Please enter the code generated by your authenticator app.', 'ebakim-wp'); ?></em></p>

        <p>
            <input type="submit" class="button button-primary" value="<?php echo esc_attr__('Submit', 'ebakim-wp'); ?>">
            <a href="<?php echo esc_url(admin_url('admin.php?page=ebakim-dashboard')); ?>" class="button"><?php echo esc_html__('Cancel', 'ebakim-wp'); ?></a>
        </p>
    </form>
</div>
