<div class="wrap">
    <h1><?php echo esc_html__('Enable 2FA', 'ebakim-wp'); ?></h1>

    <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
        <input type="hidden" name="action" value="enable_2fa_process">

        <p><?php echo esc_html__('Scan the QR code below using your authenticator app and enter the code to enable 2FA for your account.', 'ebakim-wp'); ?></p>

        <img src="<?php echo esc_url($qr_code_image_url); ?>" alt="<?php echo esc_attr__('2FA QR Code', 'ebakim-wp'); ?>">

        <label for="enable_2fa_code"><?php echo esc_html__('Enter 2FA Code', 'ebakim-wp'); ?></label>
        <input type="text" name="enable_2fa_code" id="enable_2fa_code" required>

        <p><em><?php echo esc_html__('Please enter the code generated by your authenticator app.', 'ebakim-wp'); ?></em></p>

        <p>
            <input type="submit" class="button button-primary" value="<?php echo esc_attr__('Enable 2FA', 'ebakim-wp'); ?>">
            <a href="<?php echo esc_url(admin_url('admin.php?page=ebakim-dashboard')); ?>" class="button"><?php echo esc_html__('Cancel', 'ebakim-wp'); ?></a>
        </p>
    </form>
</div>
